### ISSUE TITLE
是否支持PHP 7+ ？

### ISSUE THREAD

**Issue by Astraeux** [del-xiong/screw-plus#1]
请问对PHP各版本支持情况如何？比如PHP 7+

**Comment by del-xiong** [comment]
测试过php5.6+包括php7  其他版本的应该也可以但没有具体测试

**Comment by eqyun** [comment]
PHP_VERSION : 7.2.4
Warning: PHP Startup: php_screw_plus: Unable to initialize module
Module compiled with module API=20160303
PHP    compiled with module API=20170718
