### ISSUE TITLE
composer 命令报错

### ISSUE THREAD

**Issue by wolinyy** [del-xiong/screw-plus#19]
安装扩展后，加密laravel5.6版本的项目，再执行composer会报错：
Warning: Unexpected character in input:  ' in phar:///usr/bin/composer/bin/composer on line 57

另外：php artisan执行后，新添加的命令也无法执行

![image](https://user-images.githubusercontent.com/10389509/51901695-38e3f780-23f3-11e9-811f-29583cce4293.png)

**Comment by huacaizhi** [comment]
php7.1遇到同样的问题，安装扩展之后加密解密都木有问题，但是 composer 完全没法用了
composer -v 也报错

**Comment by smismile** [comment]
7.1 7.2都试过了，确实报错，注释掉就不再报错

**Comment by del-xiong** [comment]
已修复
