### ISSUE TITLE
make时报错了，怎么解决呢？

### ISSUE THREAD

**Issue by helloweba** [del-xiong/screw-plus#2]
[root@localhost screw_plus]# make
/bin/sh /home/screw_plus/libtool --mode=link cc -DPHP_ATOM_INC -I/home/screw_plus/include -I/home/screw_plus/main -I/home/screw_plus -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -o php_screw_plus.la -export-dynamic -avoid-version -prefer-pic -module -rpath /home/screw_plus/modules  php_screw_plus.lo 
libtool: link: `php_screw_plus.lo' is not a valid libtool object
make: *** [php_screw_plus.la] 错误 1

环境centOS7.0， PHP 7.0.7

**Comment by del-xiong** [comment]
没遇到过，可能和软件版本有关系，尝试升级下libtool然后make distclean再试试?
