### ISSUE TITLE
php5.5.1编译时报错 

### ISSUE THREAD

**Issue by fox85810** [del-xiong/screw-plus#23]
/bin/sh /root/screw-plus-master/libtool --mode=compile cc  -I. -I/root/screw-plus-master -DPHP_ATOM_INC -I/root/screw-plus-master/include -I/root/screw-plus-master/main -I/root/screw-plus-master -I/Data/apps/php/include/php -I/Data/apps/php/include/php/main -I/Data/apps/php/include/php/TSRM -I/Data/apps/php/include/php/Zend -I/Data/apps/php/include/php/ext -I/Data/apps/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/screw-plus-master/php_screw_plus.c -o php_screw_plus.lo
mkdir .libs
 cc -I. -I/root/screw-plus-master -DPHP_ATOM_INC -I/root/screw-plus-master/include -I/root/screw-plus-master/main -I/root/screw-plus-master -I/Data/apps/php/include/php -I/Data/apps/php/include/php/main -I/Data/apps/php/include/php/TSRM -I/Data/apps/php/include/php/Zend -I/Data/apps/php/include/php/ext -I/Data/apps/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/screw-plus-master/php_screw_plus.c  -fPIC -DPIC -o .libs/php_screw_plus.o
/root/screw-plus-master/php_screw_plus.c: 在函数‘pm9screw_compile_file’中:
/root/screw-plus-master/php_screw_plus.c:95: 错误：提供给函数‘zend_fopen’的实参太少
/root/screw-plus-master/php_screw_plus.c:97: 错误：提供给函数‘org_compile_file’的实参太少
/root/screw-plus-master/php_screw_plus.c:106: 错误：提供给函数‘org_compile_file’的实参太少
make: *** [php_screw_plus.lo] 错误 1
能帮忙解决一下吗

**Comment by del-xiong** [comment]
不再考虑低版本兼容性
