### ISSUE TITLE
编译成功后PHP不加载扩展

### ISSUE THREAD

**Issue by barood** [del-xiong/screw-plus#24]
PHP7.3编译成功后，扩展写入php.ini也不加载

**Comment by del-xiong** [comment]
请提供下环境信息

**Comment by qinguoqing** [comment]
php版本信息如下：
`PHP 7.2.6 (cli) (built: Jul 20 2018 09:39:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies`

执行的时候报错：
`PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'php_screw_plus.so' in Unknown on line 0`

PHP 5.6下是可以使用的，升级到PHP7后，就使用不了，请帮忙看看，谢谢。

**Comment by del-xiong** [comment]
升级之后是否有重新编译呢

**Comment by jacksonhou** [comment]
我是php7.1的环境也是同样，能编译成功，但是使用不了
`
The file "/www/wwwroot/cloudpre.xxx.com/config/routes/../../src/Controller/AdminController.php" does not contain PHP code. Did you forgot to add the "<?php" start tag at the beginning of the file? in /www/wwwroot/cloudpre.xxx.com/config/routes/../../src/Controller/ (which is being imported from "/www/wwwroot/cloudpre.xxx.com/config/routes/annotations.yaml"). Make sure annotations are installed and enabled.
`
