### ISSUE TITLE
docker 放入 php_screw_plus.so

### ISSUE THREAD

**Issue by wsx90315** [del-xiong/screw-plus#31]
想请问能在docker容器中放入
不同环境产的php_screw_plus.so档跟修改php.ini设定档吗?

类似下面dockerfile 段落
`COPY config/php_screw_plus.so /usr/lib/php7/modules/`
`RUN echo "extension=php_screw_plus.so" >> /etc/php7/php.ini`

测过只能使用在dockerfile 执行make产 php_screw_plus.so档
还是我的设定上需要调整

我容器使用的环境
`PHP 7.2.26 (cli) (built: Dec 22 2019 06:01:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies`

**Comment by del-xiong** [comment]
你应该放入对应API版本编译产生的so
例如对应7.2的环境 你也应该放入来自同一个环境编译的文件，如果不能，有可能会加载失败
