### ISSUE TITLE
whether it support php 8.0.3 or not?

### ISSUE THREAD

**Issue by Jack7244** [del-xiong/screw-plus#36]
/usr/local/php8/code/php-screw-plus/php_screw_plus.c:73:85: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 ZEND_API zend_op_array *(*org_compile_file)(zend_file_handle *file_handle, int type TSRMLS_DC);
                                                                                     ^
/usr/local/php8/code/php-screw-plus/php_screw_plus.c:75:87: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 ZEND_API zend_op_array *pm9screw_compile_file(zend_file_handle *file_handle, int type TSRMLS_DC)
                                                                                       ^
/usr/local/php8/code/php-screw-plus/php_screw_plus.c: In function ‘zm_startup_php_screw_plus’:
/usr/local/php8/code/php-screw-plus/php_screw_plus.c:145:3: error: ‘org_compile_file’ undeclared (first use in this function)
   org_compile_file = zend_compile_file;
   ^
/usr/local/php8/code/php-screw-plus/php_screw_plus.c:145:3: note: each undeclared identifier is reported only once for each function it appears in
/usr/local/php8/code/php-screw-plus/php_screw_plus.c:146:23: error: ‘pm9screw_compile_file’ undeclared (first use in this function)
   zend_compile_file = pm9screw_compile_file;
                       ^
/usr/local/php8/code/php-screw-plus/php_screw_plus.c: In function ‘zm_shutdown_php_screw_plus’:
/usr/local/php8/code/php-screw-plus/php_screw_plus.c:153:23: error: ‘org_compile_file’ undeclared (first use in this function)
   zend_compile_file = org_compile_file;
make: *** [php_screw_plus.lo] Error 1

**Comment by hoowa** [comment]
i put new php encoder project in github, it supported PHP 8.X and JIT enviroment. access https://github.com/hoowa/PHP-FRICC2 for details.

**Comment by del-xiong** [comment]
already supported please update to the newest version & retry
