### ISSUE TITLE
编译so后的问题

### ISSUE THREAD

**Issue by ScriptElite** [del-xiong/screw-plus#40]
编译了7.4下的so文件，又编译了7.3下的so文件，
用一个php文件在7.4下加密后，拿到7.3上不能使用，有遇到这样清情况的吗？

**Comment by del-xiong** [comment]
正常来说不会遇到这种问题，我测试php7跨版本到8都正常
确保2个版本都安装扩展正确，并且key一致，查看执行报错信息是什么，如果仍然不能解决可加群看看

**Comment by ScriptElite** [comment]
好的，我加一下群，谢谢解答！
