### ISSUE TITLE
请问能否迁移运行环境

### ISSUE THREAD

**Issue by b-lan** [del-xiong/screw-plus#5]
比如我在php5.5动态编译，如果我提取这个so文件当我重装服务器再安装php(或许版本会高于5.5)之后不知可否直接添加这个so文件和修改php.ini

**Comment by b-lan** [comment]
我记得ioncube能在yum上通过rpm安装而不需要每次都动态编译，不知可否实现

**Comment by del-xiong** [comment]
换环境可能会有问题，如果我没记错，iconcube是给每个环境都准备了独立的so
