### ISSUE TITLE
不明白为什么用md5

### ISSUE THREAD

**Issue by yule2001** [del-xiong/screw-plus#8]
感谢提供扩展！
只是我看源码，md5(CAKEY)的使用很疑惑，为什么不直接指定一个md5后的new_key，而是每次动态运算？
如果是指定值，那么理论上应该不必再加载md5模块，而且也不必再每次计算，是否更好？

**Comment by del-xiong** [comment]
非强制要求习惯而已，喜欢把key hash一下
也有一些额外好处,比如满足某些用户用中文 日文当密码的爱好
md5计算速度极快 性能损失几乎不用考虑
