### ISSUE TITLE
网上已经出现这个加密的破解

### ISSUE THREAD

**Issue by eveinzz** [del-xiong/screw-plus#9]
提供so和加密文件可百分百解密，

老大是否考虑再升级加强一下呢？因为有些场景，比如程序给客户了，客户自己的服务器，这种场景很常见，然后他肯定有SO也有加密文件！

**Comment by del-xiong** [comment]
可以 我空了可以升级下将解密算法只加载到内存中 获取so也无用

**Comment by GooglePlugin** [comment]
请问现在您有空升级这个扩展吗？
如果可以的话，麻烦您升级一下，我现在有一个项目需要这个扩展加密，谢谢！

**Comment by eveinzz** [comment]
继续顶起，望老大升级一下！

**Comment by gitmagox** [comment]
这个很容易破解:
ZEND_API zend_op_array *(*org_compile_file)(zend_file_handle *file_handle, int type TSRMLS_DC);
PHP_MINIT_FUNCTION(php_screw)
{
	// CG(extended_info) = 1;
	org_compile_file = zend_compile_file;
	zend_compile_file = pm9screw_compile_file;
	return SUCCESS;
}
PHP_MSHUTDOWN_FUNCTION(php_screw)
{
	// CG(extended_info) = 1;
	zend_compile_file = org_compile_file;
	return SUCCESS;
}
org_compile_file 取到了zend_compile_file中的函数地址 同理在其他扩展中也可以通过这个函数 提取出解密后的fd，拿到fd，就可以输出解密后的文档

**Comment by chisaato** [comment]
现在的SO太脆弱了,文本编辑器打开都能看到Key,如果可以把SO里面的字符串混淆就更好了.

**Comment by lobtao** [comment]
> 现在的SO太脆弱了,文本编辑器打开都能看到Key,如果可以把SO里面的字符串混淆就更好了.

此key非彼key吧

**Comment by hubyao** [comment]
大佬求更新

**Comment by del-xiong** [comment]
高强度版本，可防服务端破解
https://github.com/del-xiong/screw-opcode

@hackgyj @hubyao
